# Generated by Django 5.2.7 on 2025-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_alter_comments_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
